# permissions for end users to edit httplisteners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: httplistener-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: control-plane
    app.kubernetes.io/part-of: control-plane
    app.kubernetes.io/managed-by: kustomize
  name: httplistener-editor-role
rules:
- apiGroups:
  - apigateway.riverphillips.dev
  resources:
  - httplisteners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigateway.riverphillips.dev
  resources:
  - httplisteners/status
  verbs:
  - get
